### ISSUE TITLE
flottflott doesn't resolve

### ISSUE THREAD

**Issue by maschad96** [klippx/operator-mono-atom#3]
I've followed all steps. Fira Code font is resolving, just not flottflott.

**Comment by maschad96** [comment]
Oh, one thing that I forgot to mention is that I couldn't find the Shadow DOM option anywhere

**Comment by klippx** [comment]
Hi @floppyTop,

Thanks for checking out the repo!

Are you on mac os? Check your Font Book app in mac os, should look like this:
<img width="886" alt="screen shot 2017-05-30 at 12 59 32" src="https://cloud.githubusercontent.com/assets/2785359/26580337/ea7c1e60-4537-11e7-8ed0-3daa14097873.png">

About Shadow DOM, that was on previous Atom version < v1.13 - I removed it from the readme.

Can you give me some more information if this resolves your problem?

**Comment by mmn6d6d6e** [comment]
![image](https://user-images.githubusercontent.com/19344000/29318467-4b86080c-81fa-11e7-8c1b-82507c194aad.png)

![image](https://user-images.githubusercontent.com/19344000/29318472-520a497c-81fa-11e7-9194-44daf68de814.png)

@floppyTop 
missing semicolon on line 23

**Comment by klippx** [comment]
Thanks! Fixed in 922a608259aad34a5119283a874f081c9ae663e4

The styles.less is more updated / correct in the theme repo, plugin found at https://atom.io/themes/operator-mono
