### ISSUE TITLE
Enable this font with ligatures in Sublime Text

### ISSUE THREAD

**Issue by garciaErick** [klippx/operator-mono-atom#6]
Hello I was wondering if you can enable this font with ligatures in other text editors or IDE's for example sublime text

**Comment by klippx** [comment]
Hi, 

I have tried making this work in VS Code but haven't succeeded. Atom is easier to hack in that sense. As for Sublime Text, I'm sorry, but I do not have any interest in that editor. I really think it is ancient and you should switch to VS Code or Atom 🤷🏻‍♀️

**Comment by garciaErick** [comment]
Haha I really have no interest in those editors at all. If I use a editor I want it to load as fast and be as barebones as possible with flexibility to customize. If I want features I just use IntelliJ idea which is way better if you want features than VSCode of Atom.

**Comment by klippx** [comment]
Sorry, didn’t mean to insult you or your editor of choice.

For me atom/vscode is capable enough without going to the heavy tools (I
don’t like IDEs). If I want really light/barebone stuff instead, I would
use vim.

This is my opinion, but I used sublime for a long time, and nowadays I find
not modern enough (eg its package manager for instance 😩)
fre 25 maj 2018 kl. 10:29 skrev Erick Garcia <notifications@github.com>:

**Comment by garciaErick** [comment]
None offense taken ;)... Same here, vim shall always be my one true love, sadly I don't feel as comfortable in it on windows. Do you use your font for programing? I currently use Fira Code

**Comment by klippx** [comment]
Fira Code in VS Code is my choice for now. When I fire up Atom once in a
while I actually use these settings still just for the fun 😅
fre 25 maj 2018 kl. 16:08 skrev Erick Garcia <notifications@github.com>:

**Comment by garciaErick** [comment]
Dude, I just started working for a major company on my first job after my MS... You may have changed my destiny, I was just about to buy ST3... because tbh Atom's performance sucks. However VSCode is awesome I am so surprised... it is like Sublime's performance but I believe it may actually be objectively better, thanks!

**Comment by klippx** [comment]
Wow dude 👌🏼 I’m so happy you like it!

Yea it has a lot of momentum right now if you look at their issue tracker
and the stars/day year by year is stunning. It really is something isn’t it
👍🏼
fre 25 maj 2018 kl. 23:16 skrev Erick Garcia <notifications@github.com>:
